<?php
/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Bijstaan
 */

namespace GlpiPlugin\Glpimail;

/**
 * The optional stylesheet, and why it is optional.
 *
 * GLPI puts whatever this returns inside a `<style>` block in the head of every
 * notification. For most of this plugin's life that block carried the design's
 * modern half — a dark card, and the rules that stack a labelled row above its
 * value on a narrow screen. It is now **off unless asked for**, and the reason
 * is a measurement rather than a preference.
 *
 * ### What it costs
 *
 * Mailpit scores a message against caniemail's client-support tables, weighted
 * by client share. Measured on a real ticket notification, with everything else
 * held constant:
 *
 * ```
 * card alone, no stylesheet ......... 99.5% supported
 * + @media and !important ........... 89.0% supported
 * ```
 *
 * `@media` is supported outright by about a third of the clients in that table
 * and `!important` by fewer than half — and every rule here needs `!important`,
 * because each one is overriding an inline style or a `bgcolor` attribute,
 * which is the only thing that beats them.
 *
 * ### Why it still exists
 *
 * Because for the readers whose client *does* honour it, the difference is a
 * designed dark card instead of whatever that client's own inverter makes of a
 * white one — and Apple Mail and Outlook will invert an unanswered message
 * themselves. That is a real gain, paid for by the readers whose client
 * ignores the block and falls back to the card underneath.
 *
 * Which side of that trade a site wants is a site's decision, so it is a
 * setting, and the settings page states the score on both sides rather than
 * describing the choice in adjectives.
 *
 * ### The line this file used to rescue
 *
 * GLPI appends its own footer *after* the template body and inside `<body>`:
 *
 *     … $template_datas['content_html']
 *       . "<br>" . htmlescape($footer_string)   // "Automatically generated by X"
 *
 * It is a bare text node with no element around it, so no selector reaches it
 * and no inline style can be put on it. The only handle is what `body`
 * inherits, which is what the `body` rule below is for — and which means that
 * with enhancements off, that line arrives in the client's default type. It is
 * one line of small print under a finished card; it was not worth ten points.
 */
final class Css
{
    public static function build(Theme $theme, bool $enhancements): string
    {
        if (!$enhancements) {
            // Deliberately empty rather than a comment. GLPI emits the `<style>`
            // element whatever this returns — that tag is already counted
            // against the message and cannot be avoided from here — so the only
            // thing left to control is whether anything inside it costs more.
            return '';
        }

        $out = [];

        $out[] = '/* Generated by the glpimail plugin. Edits are lost on the next apply. */';

        // Tell the client the message has both modes, so it hands the reader
        // ours instead of running its own inverter over the light one.
        $out[] = ':root { color-scheme: light dark; supported-color-schemes: light dark; }';

        // --------------------------------------------------------- the body

        $out[] = 'body {';
        $out[] = '    margin: 0 !important;';
        $out[] = '    padding: 0 !important;';
        $out[] = '    width: 100% !important;';
        $out[] = sprintf('    background-color: %s !important;', $theme->light('ground'));
        // Inherited by GLPI's appended footer line. See the class comment.
        $out[] = sprintf('    color: %s !important;', $theme->light('muted'));
        $out[] = '    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif !important;';
        $out[] = '    font-size: 12px !important;';
        $out[] = '    text-align: center !important;';
        $out[] = '    -webkit-text-size-adjust: 100%;';
        $out[] = '    -ms-text-size-adjust: 100%;';
        $out[] = '}';

        $out[] = 'table { border-collapse: collapse !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }';

        // iOS turns anything that resembles a date, a phone number or an
        // address into a blue link of its own choosing. In a card full of dates
        // that is most of the card.
        $out[] = 'a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; }';

        // ------------------------------------------------------ narrow screens

        // 600px is the card. Below it there is no room for a two-column
        // label/value grid, so the labelled rows stack.
        //
        // `tbody` is in that list for a reason. The browser inserts one between
        // `<table>` and `<tr>` whether the markup has it or not, and it stays
        // `display: table-row-group` when its table is switched to
        // `display: block` — so the rows' containing block becomes an anonymous
        // table box that shrinks to fit its text. Measured: 71px where 311px
        // was expected.
        $out[] = '@media only screen and (max-width: 600px) {';
        $out[] = '    .gm-edge { width: 100% !important; }';
        $out[] = '    .gm-stack, .gm-stack tbody, .gm-stack tr, .gm-stack td { display: block !important; width: 100% !important; box-sizing: border-box !important; }';
        // The 12px spacer column between label and value is a cell too, and a
        // stacked one becomes a 12px-tall gap in the middle of the row.
        $out[] = '    .gm-stack td[width="12"] { display: none !important; }';
        $out[] = '    .gm-title { font-size: 20px !important; }';
        $out[] = '}';

        // ---------------------------------------------------------- dark mode

        $out[] = '@media (prefers-color-scheme: dark) {';
        $out[] = sprintf('    body, .gm-ground, .gm-ground td { background-color: %s !important; }', $theme->dark('ground'));
        $out[] = sprintf('    body { color: %s !important; }', $theme->dark('muted'));
        $out[] = sprintf('    .gm-edge, .gm-edge td { background-color: %s !important; }', $theme->dark('border'));
        $out[] = sprintf('    .gm-card { background-color: %s !important; }', $theme->dark('card'));
        $out[] = sprintf('    .gm-head, .gm-head td { background-color: %s !important; }', $theme->dark('faint'));
        $out[] = sprintf('    .gm-title, .gm-ink, .gm-value td { color: %s !important; }', $theme->dark('ink'));
        $out[] = sprintf('    .gm-body, .gm-body td { color: %s !important; }', $theme->dark('ink'));
        $out[] = sprintf('    .gm-muted, .gm-label, .gm-label td, .gm-foot, .gm-eyebrow { color: %s !important; }', $theme->dark('muted'));
        $out[] = sprintf('    .gm-panel-body { background-color: %s !important; }', $theme->dark('faint'));
        $out[] = sprintf('    .gm-panel-bar { background-color: %s !important; }', $theme->dark('accent'));
        // The hairlines are `bgcolor` on the cells themselves, not on anything
        // that contains them. Aimed at a container this leaves a near-white
        // line drawn across a near-black card, which is the most visible way a
        // dark mode can be almost right.
        $out[] = sprintf('    .gm-hr { background-color: %s !important; }', $theme->dark('hairline'));
        $out[] = sprintf('    .gm-link, .gm-body a { color: %s !important; }', $theme->dark('accent'));
        // The button is the one thing that does not follow the page: its ground
        // is the brand accent in both modes, so its ink follows the accent and
        // not the page. See Theme.
        $out[] = sprintf('    .gm-btn { background-color: %s !important; }', $theme->dark('accent'));
        $out[] = sprintf('    .gm-btn-a { color: %s !important; }', $theme->dark('accent_ink'));
        $out[] = sprintf('    .gm-rule { background-color: %s !important; }', $theme->dark('accent'));

        foreach (Theme::darkTones() as $tone => [$bg, $ink, $border]) {
            $out[] = sprintf('    .gm-pill-%s { background-color: %s !important; }', $tone, $border);
            $out[] = sprintf('    .gm-pill-fill-%s { background-color: %s !important; }', $tone, $bg);
            $out[] = sprintf('    .gm-pill-fill-%s td { color: %s !important; }', $tone, $ink);
        }

        $out[] = '}';

        return implode("\n", $out) . "\n";
    }
}
