<?php
/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Bijstaan
 */

namespace GlpiPlugin\Glpimail;

use NotificationTemplate;

/**
 * What the mail will actually look like.
 *
 * A settings page that shows an accent swatch has told you the accent. It has
 * not told you that the button is unreadable, that the status pill wraps, or
 * that a logo drawn for a dark sidebar has vanished into the masthead. The
 * only way to know is to look at the thing, and the only honest version of the
 * thing is the one GLPI is going to send.
 *
 * So the preview is not an approximation of the send path — it *is* the send
 * path, minus the recipient:
 *
 *  - the body comes from {@see Catalog} through {@see Shell}, exactly as
 *    {@see Templates::apply()} would write it;
 *  - the tags are substituted by {@see \NotificationTemplate::process()},
 *    GLPI's own code, so a malformed `##IF##` or a `##FOREACH##` naming a list
 *    that does not exist fails here in the same way it would fail in an inbox
 *    rather than being quietly rendered by something more forgiving;
 *  - the wrapper is rebuilt the way
 *    {@see \NotificationTemplate::getTemplateByLanguage()} builds it, down to
 *    the "Automatically generated by …" line GLPI appends after the body.
 *
 * That last one matters more than it sounds. That line is the reason
 * {@see Css} styles `body` at all, and a preview that omitted it would be
 * hiding the one piece of the layout this plugin does not control.
 */
final class Preview
{
    /**
     * The complete document, ready to put in an iframe.
     *
     * @param string $name a template name from the catalog
     */
    public static function render(string $name): string
    {
        $catalog = Catalog::all();
        $entry   = $catalog[$name] ?? null;

        $brand = Brand::resolve();
        $theme = Theme::fromAccent($brand->accent);
        $shell = new Shell($theme, $brand);

        $blocks = $entry !== null ? $entry['blocks'] : self::placeholder();
        $html   = $shell->html($blocks);
        $css    = Css::build($theme, Settings::flag('enhancements'));

        $subject = $entry !== null
            ? $name
            : __('Sample notification', 'glpimail');

        return self::wrap($subject, $css, self::fill($html));
    }

    /**
     * Rebuild GLPI's own wrapper.
     *
     * Kept deliberately close to the original in NotificationTemplate, footer
     * line and all, so that what is on screen and what lands in an inbox differ
     * only in who sent them. The one addition is a `<base target="_blank">`,
     * because this is rendered in an iframe on the settings page and a link
     * followed inside it would replace the preview with GLPI.
     */
    private static function wrap(string $subject, string $css, string $body): string
    {
        global $CFG_GLPI;

        $footer = sprintf(__('Automatically generated by %s'), $CFG_GLPI['app_name'] ?? 'GLPI');

        return '<!DOCTYPE html><html><head>'
             . '<meta charset="utf-8" />'
             . '<meta name="viewport" content="width=device-width, initial-scale=1" />'
             . '<base target="_blank" />'
             . '<title>' . htmlspecialchars($subject, ENT_QUOTES, 'UTF-8') . '</title>'
             . '<style type="text/css">' . $css . '</style>'
             . '</head><body>' . "\n"
             . $body
             . '<br>' . htmlspecialchars($footer, ENT_QUOTES, 'UTF-8')
             . '<br><br>' . "\n"
             . '</body></html>';
    }

    // ============================================================ sample data

    /**
     * Fill the tags with something plausible, using GLPI's own processor.
     *
     * Public because the container-side test in tests/process.php renders every
     * template through it and then asserts that no `##…##` survived — which is
     * the only way to prove a body's tag syntax against the code that will
     * actually read it.
     *
     * The data is invented here rather than read from a real ticket on purpose.
     * A preview built from live data is a preview whose usefulness depends on
     * what happens to be in the database — an instance where every ticket is
     * one line long never shows what a long description does to the card, and
     * an instance with no solved tickets never renders the solution section at
     * all. These values are chosen to exercise the layout: a title long enough
     * to wrap, a description with a paragraph and a list in it, and every
     * conditional branch given something to show.
     */
    public static function fill(string $html): string
    {
        $data = self::values($html);

        // The loop rows are built from the *scalar* values only. Reading them
        // out of $data as it is being extended would hand the second loop the
        // first loop's array of rows and vary() a list of lists.
        $scalars = $data;

        foreach (self::loops($html) as $loop) {
            $data[$loop] = self::rows($loop, $scalars);
        }

        return NotificationTemplate::process($html, $data, true);
    }

    /**
     * Every `##tag##` in the body, with a value invented for it.
     *
     * @return array<string,string>
     */
    private static function values(string $html): array
    {
        preg_match_all('/##([a-z0-9][a-z0-9._-]*)##/i', $html, $found);

        // A field used only as a condition — `##IFticket.storestatus=5##` —
        // never appears as a bare `##tag##`, so the sweep above misses it and
        // processIf() then finds nothing in $data and takes the ELSE branch
        // for everything. A preview that silently shows only else-branches is
        // worse than no preview: it looks like the design, and it is half of it.
        preg_match_all('/##(?:IF|ELSE|ENDIF|ENDELSE)([a-z0-9._-]+?)(?:=[^#]*)?##/i', $html, $conditions);

        $data = [];

        foreach (array_unique(array_merge($found[1], $conditions[1])) as $tag) {
            if (preg_match('/^(IF|ELSE|ENDIF|ENDELSE|FOREACH|ENDFOREACH)/', $tag) === 1) {
                continue;
            }

            $data['##' . $tag . '##'] = self::value($tag);
        }

        return $data;
    }

    /** @return array<int,string> the names of the FOREACH lists used */
    private static function loops(string $html): array
    {
        preg_match_all('/##FOREACH(?:\s+(?:FIRST|LAST)\s+\d+)?\s*([a-z0-9_]+)##/i', $html, $found);

        return array_values(array_unique($found[1]));
    }

    /**
     * The rows one FOREACH list produces.
     *
     * Three of them, because one hides a spacing bug between rows and two hides
     * an off-by-one in a separator.
     *
     * @param array<string,string> $data
     * @return array<int,array<string,string>>
     */
    private static function rows(string $loop, array $data): array
    {
        $rows = [];

        for ($i = 1; $i <= 3; $i++) {
            $row = [];

            foreach ($data as $tag => $value) {
                $row[$tag] = self::vary($tag, $value, $i);
            }

            $rows[] = $row;
        }

        return $rows;
    }

    private static function vary(string $tag, string $value, int $index): string
    {
        return match (true) {
            str_contains($tag, '.name##'), str_contains($tag, '.title##'), str_contains($tag, '.item##')
                => $value . ' ' . $index,
            str_contains($tag, '.id##')
                => (string) (1000 + $index),
            default => $value,
        };
    }

    /**
     * One tag's sample value.
     *
     * `##lang.a.b##` is a label, so it is rendered as one — "Solve date" from
     * `lang.ticket.solvedate`. Everything else is matched on the last segment
     * of its name, which is what actually decides its shape: anything ending
     * `date` is a date wherever it appears, and `url` is a link on a ticket,
     * a licence or a saved search alike.
     */
    private static function value(string $tag): string
    {
        global $CFG_GLPI;

        if (str_starts_with($tag, 'lang.')) {
            $words = explode('.', $tag);
            $last  = (string) end($words);

            // GLPI's own labels are whole translated phrases, and the tag name
            // is a squashed version of one — `commentvalidation`, `solvedate`,
            // `numberoffollowups`. Un-squashing them by rule is not possible;
            // this is the short list of the ones that appear in the catalog,
            // so the preview shows a column of labels rather than a column of
            // run-together words that make the design look worse than it is.
            $known = [
                'solvedate'         => 'Solve date',
                'closedate'         => 'Close date',
                'creationdate'      => 'Creation date',
                'duedate'           => 'Due date',
                'expirationdate'    => 'Expiration date',
                'dateexpiration'    => 'Expiration date',
                'planstartdate'     => 'Planned start',
                'planenddate'       => 'Planned end',
                'submissiondate'    => 'Submitted on',
                'validationdate'    => 'Answered on',
                'assigntousers'     => 'Assigned to',
                'assigntogroups'    => 'Assigned to group',
                'requesttype'       => 'Request type',
                'numberoffollowups' => 'Followups',
                'numberoftasks'     => 'Tasks',
                'numberofdocuments' => 'Documents',
                'commentsubmission' => 'Request comments',
                'commentvalidation' => 'Approval comments',
                'timelineitems'     => 'Recent activity',
                'stock_target'      => 'Stock target',
                'to_order'          => 'To order',
                'sla_ttr'           => 'Time to resolve',
                'attribution'       => 'Assigned to',
                'is_faq'            => 'In the FAQ',
                'plannedduration'   => 'Planned duration',
                'effectiveduration' => 'Effective duration',
                'lockedby'          => 'Locked by',
            ];

            return $known[$last] ?? ucfirst(str_replace('_', ' ', $last));
        }

        if ($tag === 'glpi.url') {
            return (string) ($CFG_GLPI['url_base'] ?? 'https://example.invalid');
        }

        $base     = (string) ($CFG_GLPI['url_base'] ?? 'https://example.invalid');
        $segments = explode('.', $tag);
        $leaf     = (string) array_pop($segments);

        return match (true) {
            str_ends_with($leaf, 'url')          => $base . '/front/central.php',
            str_ends_with($leaf, 'date')         => '2026-09-02 14:20',
            $leaf === 'id'                       => '1042',
            // Every target has an `action`, and it names what happened, so it
            // is the one tag whose value has to follow the prefix rather than
            // the leaf — "Ticket solved" over a password-reset mail is a
            // preview that teaches the reader something untrue about the
            // template they are looking at.
            $leaf === 'action'                   => self::action($tag),
            $leaf === 'title', $leaf === 'name'  => 'Laptop will not connect to the docking station in meeting room 2',
            $leaf === 'subject'                  => 'Resetting a docking station',
            $leaf === 'status'                   => 'Solved',
            $leaf === 'storestatus'              => '5',
            $leaf === 'priority'                 => 'High',
            $leaf === 'urgency', $leaf === 'impact' => 'Medium',
            $leaf === 'category'                 => 'Hardware > Peripherals',
            $leaf === 'entity'                   => 'Head office',
            $leaf === 'authors', $leaf === 'author', $leaf === 'user', $leaf === 'manager',
            $leaf === 'validator', $leaf === 'commander', $leaf === 'tech', $leaf === 'lastupdater',
            $leaf === 'openbyuser'               => 'Jordan Ellis',
            $leaf === 'realname', $leaf === 'lastname' => 'Ellis',
            $leaf === 'firstname'                => 'Jordan',
            $leaf === 'assigntousers'            => 'Sam Okonkwo',
            $leaf === 'assigntogroups'           => 'Service desk',
            $leaf === 'requesttype'              => 'Helpdesk',
            $leaf === 'content', $leaf === 'description', $leaf === 'message'
                => '<p>The dock has stopped passing video to either monitor since Tuesday. '
                 . 'Power and network still work through it.</p><ul><li>Reseated the cable</li>'
                 . '<li>Tried a second laptop, same result</li></ul>',
            $leaf === 'percent'                  => '60%',
            $leaf === 'state'                    => 'In progress',
            $leaf === 'count'                    => '12',
            $leaf === 'serial'                   => 'SN-4F81-22C',
            $leaf === 'remaining'                => '3',
            $leaf === 'version'                  => '2.1.0',
            $leaf === 'old_version'              => '2.0.4',
            $leaf === 'errors'                   => 'Authentication failed (5 attempts)',
            $leaf === 'item', $leaf === 'itemtype', $leaf === 'type', $leaf === 'typename'
                                                 => 'Computer',
            $leaf === 'reference'                => 'HP 305A cyan',
            $leaf === 'number'                   => 'C-2024-118',
            $leaf === 'time'                     => '12 months',
            $leaf === 'entity'                   => 'Head office',
            $leaf === 'delay'                    => '4 minutes',
            default                              => '—',
        };
    }

    /** What `##…action##` says, which depends on what the notification is about. */
    private static function action(string $tag): string
    {
        $prefix = (string) strtok($tag, '.');

        return match ($prefix) {
            'ticket'                  => 'Ticket solved',
            'problem'                 => 'Problem updated',
            'change'                  => 'Change submitted for approval',
            'user'                    => 'Password reset requested',
            'reservation'             => 'Reservation confirmed',
            'contract'                => 'Contract reaching its notice period',
            'license'                 => 'Licence expiring',
            'infocom'                 => 'Warranty expiring',
            'cartridge', 'consumable' => 'Stock below threshold',
            'crontask'                => 'Automatic action stalled',
            'mailcollector'           => 'Receiver failing',
            'objectlock'              => 'Unlock requested',
            'savedsearch'             => 'Saved search alert',
            'knowbaseitem'            => 'Article published',
            'project', 'projecttask'  => 'Updated',
            'recall'                  => 'Starting soon',
            'unicity'                 => 'Duplicate refused',
            default                   => ucfirst($prefix) . ' update',
        };
    }

    /** @return array<int,array<mixed>> */
    private static function placeholder(): array
    {
        return [
            ['eyebrow', 'Sample'],
            ['title', 'There is no description for this template'],
            ['lede', 'It will be wrapped in this card with its own body left exactly as it is.'],
        ];
    }
}
